name: UI Test for DemoWebshop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        TEST_PLATFORM_NAME: Windows 10
        TEST_BROWSER_NAME: chrome
        TEST_BROWSER_VERSION: latest
        SAUCELABS_NAME: Demo webshop tests
        SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
        SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }} 
        #SAUCELABS_BUILD: ${{ github.sha }}
        SAUCELABS_BUILD: ${{ github.ref_name }}
        SAUCELABS_URL: https://ondemand.eu-central-1.saucelabs.com:443/wd/hub
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
